spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ars
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: "jdbc:h2:file:C:/Users/Hili/Desktop/ea_ars/testdb"
#    driver-class-name: "org.h2.Driver"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "samsonramato@gmail.com"
    password: "walyyswxfjeodnnw"

    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  jpa:
#    database-platform: "org.hibernate.dialect.H2Dialect"