server:
  port: 80
spring:
  datasource:
    url: "jdbc:mysql://157.230.59.11:3306/ea_ars"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ea
    password: "ea_ars"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "samsonramato@gmail.com"
    password: "walyyswxfjeodnnw"

    properties:
      mail:
        smtp:
          auth: "true"


          starttls:
            enable: "true"
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: "org.hibernate.dialect.H2Dialect"

# App Properties
#spring.security.user.password: Test12345_
ea.ars.app: ea_ars