spring:
  application:
    name: ea_ars
  mail:
    host: smtp.gmail.com
    port: 587
    username: "samsonramato@gmail.com"
    password: "walyyswxfjeodnnw"

    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
             enable: "true"
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=project
    username: sa
    password: 21samgmail
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
#  security:
#    user:
#      name: user
#      password: 123456

logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 8080

