spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "samsonramato@gmail.com"
    password: "walyyswxfjeodnnw"

    properties:
      mail:
        smtp:
          auth: "true"


          starttls:
            enable: "true"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"